---

# Application settings.
virtualenv_path: "/home/ubuntu/.virtualenvs/"
project_path: "/home/ubuntu/{{ project_name }}"
requirements_file: "{{ project_path }}/requirements.txt"

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
