---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted
  sudo_user: root

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  sudo_user: root

- name: reload nginx
  service: name=nginx state=reloaded
  sudo_user: root
