---

# Database settings.
db_user: "blog_analytics"
db_name: "blog_analytics"
db_password: myawesomepassword

# Nginx settings.
nginx_server_name: "ec2-54-69-178-203.us-west-2.compute.amazonaws.com"

django_settings_file: rocketu_blog_analytics.settings