---

- name: Provision a RocketU Blog Analytics server
  hosts: all
  sudo: yes
  sudo_user: ubuntu
  remote_user: ubuntu
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml

  roles:
    - base
    - db
    - web